# Generated by Django 5.2.9 on 2025-12-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='TodoList',
        ),
    ]
