# Generated by Django 5.2.9 on 2025-12-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_todolist_is_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoList',
            new_name='Notes',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='task',
            new_name='notes_obj',
        ),
    ]
