# Generated by Django 5.2.9 on 2025-12-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_rename_todolist_notes_rename_task_notes_notes_obj'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='TodoList',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='notes_obj',
            new_name='task',
        ),
    ]
