# Generated by Django 5.2.9 on 2025-12-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_notes_todolist_rename_notes_obj_todolist_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Todo Item', 'verbose_name_plural': 'Todo Items'},
        ),
        migrations.AddField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task was created', null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the task was last updated', null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Check if the task is completed', verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='task',
            field=models.CharField(help_text='Enter the task description (max 200 characters)', max_length=200, verbose_name='Task Description'),
        ),
    ]
